apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingLot
  labels:
    app: parkingLot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingLot
  template:
    metadata:
      labels:
        app: parkingLot
    spec:
      containers:
        - name: parkingLot
          image: username/parkingLot:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5